esphome:
  name: ac

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AC Fallback Hotspot"
    password: !secret fallback_pass

captive_portal:

logger:
  baud_rate: 0

