esphome:
  name: ac

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !env_var SSID
  password: !env_var WIFI_PASS

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AC Fallback Hotspot"
    password: !env_var FALLBACK_PASS

captive_portal:

logger:
  baud_rate: 0

