name: Deployment

concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache ESPHome
        uses: actions/cache@v2
        with:
          path: ~/.esphome
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - run: pip install esphome
      - run: echo "::set-env name=COMMIT_SHA::\"$GITHUB_SHA\""
      - run: esphome run ac.yml --device ac.local --no-logs
        env:
          SSID: ${{ secrets.SSID }}
          WIFI_PASS: ${{ secrets.WIFI_PASS }}
          FALLBACK_PASS: ${{ secrets.FALLBACK_PASS }}
          COMMIT_SHA: ${{ env.COMMIT_SHA }}