name: Deployment

concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install esphome
      - run: esphome run ac.yml --device ac.local
